"""add embedding columns to student_profiles and projects

Revision ID: b1564351e1f3
Revises: c9fc3db88d6f
Create Date: 2026-09-14 09:24:34.664724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1564351e1f3'
down_revision: Union[str, None] = 'c9fc3db88d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate falsely detected a type change on milestones.status
    # (SQLite-only artifact: it compares VARCHAR against Enum, but both represent
    # the same enum conceptually in this app's schema). This is a known false
    # positive documented in c9fc3db88d6f; no alter_column is needed here.
    op.add_column('projects', sa.Column('embedding', sa.JSON(), nullable=True))
    op.add_column('student_profiles', sa.Column('embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'embedding')
    op.drop_column('projects', 'embedding')
    # ### end Alembic commands ###
