"""baseline schema

Revision ID: bb371d385f9a
Revises: 
Create Date: 2026-08-30 17:46:16.471580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb371d385f9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('primary_color', sa.String(length=9), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('license_tier', sa.Enum('TRIAL', 'STANDARD', 'ENTERPRISE', name='universitylicensetier'), nullable=False),
    sa.Column('license_status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'EXPIRED', name='universitylicensestatus'), nullable=False),
    sa.Column('license_seats', sa.Integer(), nullable=False),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('annual_fee_gbp', sa.Float(), nullable=True),
    sa.Column('primary_contact_name', sa.String(length=255), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=255), nullable=True),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_slug'), 'universities', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'BUSINESS', 'UNIVERSITY_ADMIN', 'PLATFORM_ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('university_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('business_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_registration_number', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('global_trust_tier', sa.Enum('UNVERIFIED', 'ID_VERIFIED', 'UNIVERSITY_APPROVED', 'STRATEGIC_PARTNER', name='businesstrusttier'), nullable=False),
    sa.Column('is_registration_verified', sa.Boolean(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('completed_projects_count', sa.Integer(), nullable=False),
    sa.Column('payment_promptness_score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('devices',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.Enum('IOS', 'ANDROID', 'WEB', name='deviceplatform'), nullable=False),
    sa.Column('push_token', sa.String(length=500), nullable=False),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_logs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=False),
    sa.Column('action_taken', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('university_id', sa.String(length=36), nullable=False),
    sa.Column('degree_title', sa.String(length=255), nullable=False),
    sa.Column('band', sa.Enum('FOUNDATION', 'YEAR_1', 'YEAR_2', 'YEAR_3', 'YEAR_4_PLUS', 'POSTGRAD_TAUGHT', 'POSTGRAD_RESEARCH', 'RECENT_ALUMNI', name='studentband'), nullable=False),
    sa.Column('modules', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('portfolio_urls', sa.JSON(), nullable=False),
    sa.Column('hourly_rate_expectation_gbp', sa.Float(), nullable=True),
    sa.Column('weekly_hours_available', sa.Integer(), nullable=True),
    sa.Column('right_to_work_confirmed', sa.Boolean(), nullable=False),
    sa.Column('visa_weekly_hour_cap', sa.Integer(), nullable=True),
    sa.Column('is_id_verified', sa.Boolean(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('completed_projects_count', sa.Integer(), nullable=False),
    sa.Column('on_time_rate', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('projects',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('DATA_ANALYTICS', 'SOFTWARE_ENGINEERING', 'MARKETING', 'DESIGN', 'RESEARCH', 'FINANCE', 'OPERATIONS', 'OTHER', name='projectcategory'), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('duration_label', sa.String(length=100), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('hourly_rate_gbp', sa.Float(), nullable=False),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('location_label', sa.String(length=255), nullable=True),
    sa.Column('target_university_ids', sa.JSON(), nullable=False),
    sa.Column('target_bands', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('university_business_agreements',
    sa.Column('university_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED', name='agreementstatus'), nullable=False),
    sa.Column('allowed_bands', sa.JSON(), nullable=False),
    sa.Column('allowed_categories', sa.JSON(), nullable=False),
    sa.Column('max_active_projects', sa.Integer(), nullable=True),
    sa.Column('requires_university_project_review', sa.Boolean(), nullable=False),
    sa.Column('university_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('cover_note', sa.Text(), nullable=True),
    sa.Column('proposed_rate_gbp', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'SHORTLISTED', 'INTERVIEWING', 'OFFERED', 'ACCEPTED', 'DECLINED', 'REJECTED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('match_score_at_application', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_threads',
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('student_user_id', sa.String(length=36), nullable=False),
    sa.Column('business_user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('terms_document_url', sa.String(length=500), nullable=True),
    sa.Column('ip_assignment_accepted', sa.Boolean(), nullable=False),
    sa.Column('nda_accepted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'TERMINATED', 'DISPUTED', name='contractstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('sender_user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('flagged_reason', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['message_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestones',
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_amount_gbp', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'APPROVED', 'PAID', 'DISPUTED', name='milestonestatus'), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('rater_user_id', sa.String(length=36), nullable=False),
    sa.Column('ratee_user_id', sa.String(length=36), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('sub_scores', sa.JSON(), nullable=False),
    sa.Column('private_comment', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PLATFORM_ONLY', name='ratingvisibility'), nullable=False),
    sa.Column('is_released', sa.Boolean(), nullable=False),
    sa.Column('is_flagged_for_review', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['ratee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rater_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    op.drop_table('milestones')
    op.drop_table('messages')
    op.drop_table('contracts')
    op.drop_table('message_threads')
    op.drop_table('applications')
    op.drop_table('university_business_agreements')
    op.drop_table('projects')
    op.drop_table('student_profiles')
    op.drop_table('recommendation_logs')
    op.drop_table('devices')
    op.drop_table('business_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_universities_slug'), table_name='universities')
    op.drop_table('universities')
    # ### end Alembic commands ###
