"""add university SAML SSO config fields

Revision ID: c98cf682936f
Revises: c5563aee8f62
Create Date: 2026-09-06 11:54:49.748131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98cf682936f'
down_revision: Union[str, None] = 'c5563aee8f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand, same reason as c5563aee8f62's own fix:
    # NOT NULL + no default would crash applying against a database with
    # existing rows (the real staging Postgres already has a seeded
    # university) — autogenerate doesn't add this on its own.
    op.add_column('universities', sa.Column('saml_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('universities', sa.Column('saml_idp_entity_id', sa.String(length=500), nullable=True))
    op.add_column('universities', sa.Column('saml_idp_sso_url', sa.String(length=500), nullable=True))
    op.add_column('universities', sa.Column('saml_idp_x509_cert', sa.Text(), nullable=True))
    op.add_column('universities', sa.Column('saml_attribute_mapping', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universities', 'saml_attribute_mapping')
    op.drop_column('universities', 'saml_idp_x509_cert')
    op.drop_column('universities', 'saml_idp_sso_url')
    op.drop_column('universities', 'saml_idp_entity_id')
    op.drop_column('universities', 'saml_enabled')
    # ### end Alembic commands ###
