"""add data protection fields: last_login, consent, deletion

Revision ID: c9fc3db88d6f
Revises: eede1a0f59da
Create Date: 2026-09-07 17:16:53.163429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9fc3db88d6f'
down_revision: Union[str, None] = 'eede1a0f59da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - hand-adjusted, see note below ###
    # Autogenerate also produced an alter_column on milestones.status here —
    # removed. That's the same SQLite-only false positive documented in
    # eede1a0f59da (SQLite stores every Enum as a plain VARCHAR with no
    # real constraint, so autogenerate's local-SQLite-vs-model comparison
    # spuriously "detects" a type change on every run touching this table,
    # even though MilestoneStatus's actual members haven't changed since
    # that migration). Nothing about milestonestatus changes in this one.
    op.add_column('student_profiles', sa.Column('data_sharing_consent_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - hand-adjusted, see note above ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('student_profiles', 'data_sharing_consent_at')
    # ### end Alembic commands ###
