"""add stripe payments and payroll fields

Revision ID: eede1a0f59da
Revises: c2c089143636
Create Date: 2026-09-07 11:03:12.529118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eede1a0f59da'
down_revision: Union[str, None] = 'c2c089143636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - hand-adjusted, see notes below ###
    op.create_table('processed_webhook_events',
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_webhook_events_stripe_event_id'), 'processed_webhook_events', ['stripe_event_id'], unique=True)
    op.add_column('business_profiles', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('business_profiles', sa.Column('stripe_default_payment_method_id', sa.String(length=255), nullable=True))
    # Hand-added server_default: autogenerate omitted it on this new NOT
    # NULL column, same class of bug caught in c5563aee8f62 and c98cf682936f
    # — would crash applying against any existing contracts row. Stores the
    # Python enum MEMBER NAME ('SELF_EMPLOYED'), not its value
    # ('self_employed') — matches how every other str Enum column in this
    # schema is stored (see bb371d385f9a's UserRole/BusinessTrustTier etc.).
    op.add_column('contracts', sa.Column(
        'payment_rail',
        sa.Enum('SELF_EMPLOYED', 'PAYE_UMBRELLA', name='paymentrail'),
        nullable=False,
        server_default='SELF_EMPLOYED',
    ))
    op.add_column('milestones', sa.Column('stripe_payment_intent_status', sa.String(length=50), nullable=True))
    op.add_column('milestones', sa.Column('authorized_at', sa.DateTime(), nullable=True))
    op.add_column('milestones', sa.Column('captured_at', sa.DateTime(), nullable=True))
    op.add_column('milestones', sa.Column('payroll_exported_at', sa.DateTime(), nullable=True))

    # Hand-replaced: autogenerate produced an `alter_column(..., type_=Enum(...))`
    # here, comparing against SQLite's fallback VARCHAR(9) representation of
    # the OLD enum (this migration was generated against a local SQLite DB —
    # see CLAUDE.md's "Dependency pinning"/migration notes on why SQLite is
    # the dev default). On real Postgres, `milestonestatus` is a genuine
    # native ENUM type (created in bb371d385f9a) with only the original 5
    # values — a generic ALTER COLUMN TYPE does not add new labels to an
    # existing Postgres enum type; it needs explicit `ALTER TYPE ... ADD
    # VALUE` statements instead, or every AUTHORIZATION_FAILED/REFUNDED
    # this codebase ever tries to write would fail at the database with
    # "invalid input value for enum milestonestatus". SQLite has no
    # equivalent native enum constraint to update, so this only runs
    # against Postgres.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("ALTER TYPE milestonestatus ADD VALUE IF NOT EXISTS 'AUTHORIZATION_FAILED'")
        op.execute("ALTER TYPE milestonestatus ADD VALUE IF NOT EXISTS 'REFUNDED'")
        op.execute("ALTER TYPE milestonestatus ADD VALUE IF NOT EXISTS 'REJECTED'")

    op.add_column('student_profiles', sa.Column('stripe_connect_account_id', sa.String(length=255), nullable=True))
    # Hand-added server_default — same reasoning as payment_rail above.
    op.add_column('student_profiles', sa.Column(
        'stripe_connect_onboarded', sa.Boolean(), nullable=False, server_default=sa.false(),
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - hand-adjusted, see notes above ###
    op.drop_column('student_profiles', 'stripe_connect_onboarded')
    op.drop_column('student_profiles', 'stripe_connect_account_id')
    # Deliberately does NOT remove the two added enum labels — Postgres has
    # no `ALTER TYPE ... DROP VALUE`, and rewriting the whole enum type to
    # shrink it isn't worth the risk for a downgrade path. Any
    # AUTHORIZATION_FAILED/REFUNDED/REJECTED rows written while upgraded
    # would need to be migrated to another status by hand before a real downgrade —
    # same category of known, documented, non-urgent gap as the ENUM-drop
    # note already in app/db/migrations.py for the baseline migration.
    op.drop_column('milestones', 'payroll_exported_at')
    op.drop_column('milestones', 'captured_at')
    op.drop_column('milestones', 'authorized_at')
    op.drop_column('milestones', 'stripe_payment_intent_status')
    op.drop_column('contracts', 'payment_rail')
    op.drop_column('business_profiles', 'stripe_default_payment_method_id')
    op.drop_column('business_profiles', 'stripe_customer_id')
    op.drop_index(op.f('ix_processed_webhook_events_stripe_event_id'), table_name='processed_webhook_events')
    op.drop_table('processed_webhook_events')
    # ### end Alembic commands ###
